### ISSUE TITLE
Fails to visualize compose files which use the "runtime" option.

### ISSUE THREAD

**Issue by tfortunato** [nautilusapp/nautilus#165]
Docker-compose files which use the "runtime" option (
https://docs.docker.com/compose/compose-file/compose-file-v2/#runtime) will fail with "Unsupported config option for <name>: 'runtime'"., and can not be visualized.

**Comment by jdnordy** [comment]
Thank for letting us know.

Can you share a screen shot of the error you are getting?

**Comment by michaelbayday** [comment]
Hi there, could you share with us your docker compose file? The file validations that we are using are directly from the docker compose CLI command so there may be a error unaccounted for but I’m happy to take a look at the bug!

Thank you!

**Comment by jdnordy** [comment]
Looked into it more. "Runtime" option is [only available in version 2.3.](https://github.com/docker/compose/pull/6240) Looks like your using invalid Compose syntax. Try changing the root level "version" key to 2.3 or 2.4 : 
```
version: '2.3'

services: 
    myapp:
       ... 
```
Or remove the "runtime" key. Hope this helps!
