### ISSUE TITLE
Upload action is confusing/troubling

### ISSUE THREAD

**Issue by smileatom** [nautilusapp/nautilus#175]
Consider changing upload to "open" or "add".  I personally need clarity when using a tool whether or not my companies compose files are "being uploaded" to someones servers or not.  One thing is 'ok' the other is 'not ok'.

I fished through your code and this "upload" appears to upload to a local webserver running the app.  But it does raise questions from the front end perspective.

**Comment by michaelbayday** [comment]
Thanks for the feedback. changes have been made and we are in the process of redeploying the download links with the latest version now
